apiVersion: v2
name: jobcontroller
description: A Helm chart to distribute jobcontroller
type: application

version: 0.1.0
appVersion: "0.1.0"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
